orbs:
  aws-s3: circleci/aws-s3@2.0.0
version: 2.1

workflows:
  build:
    jobs:
      - build:
          context: wasserraptor

jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      run: ls -lah
      - aws-s3/copy:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          arguments: '--recursive'
          from: 'site/'
          to: 's3://wasserraptorde'
