orbs:
  aws-s3: circleci/aws-s3@2.0.0
version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - aws-s3/copy:
          arguments: '--dryrun'
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: .
          to: 's3://wasserraptorde'
