orbs:
  aws-s3: circleci/aws-s3@x.y
version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - aws-s3/copy:
          arguments: '--dryrun'
          from: .
          to: 's3://wasserraptorde'
